### ISSUE TITLE
Running ./dev_setup.sh fails

### ISSUE THREAD

**Issue by sebastiandro** [AstraZeneca/rexmex#12]
There is no `setup.py` file inside the `rexmex` folder, hence the `dev_setup.sh` script fails with error message:

```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode
```

A solution could be to update the `dev_setup.sh` to install the package from the root directory:

```
pip install -e .
```

**Comment by benedekrozemberczki** [comment]
Install fixed, yml to yaml fixed and the pre-commit config is fixed
