### ISSUE TITLE
Filtered Metrics

### ISSUE THREAD

**Issue by GavEdwards** [AstraZeneca/rexmex#24]
# Filtered Metrics
Feature request: add a standard function to calculate filtered metrics. This removes recommendations that appeared in training, validation and test sets.

This could be a pre-made function. E.g

`rexmex.filter_scores(scores, training_set, validation_set, testing_set)
`

As described in this paper (described as triples in knowledge graph recommendation): 
https://papers.nips.cc/paper/2013/file/1cecc7a77928ca8133fa24680a88d2f9-Paper.pdf

![image](https://user-images.githubusercontent.com/24434382/145011899-5455b8bf-c1d2-43d2-9932-660322e9049f.png)

**Comment by benedekrozemberczki** [comment]
Love this! I will add it!

**Comment by benedekrozemberczki** [comment]
Already in, will be part of 0.0.13.
