### ISSUE TITLE
API Suggestions

### ISSUE THREAD

**Issue by cthoyt** [AstraZeneca/rexmex#27]
Right now it's a bit round-about to get a scorecard for a given dataset since it expect a pandas format. I'd suggest exposing `ScoreCard._get_performance_metrics` as a public user interface and also encourage people to use that directly in case they're generating their own y_true and y_score and don't want to write their own code to generate a pandas dataframe from it, just for `rexmex` to need to unpack it. 

My example is in PyKEEN, where we do just that: https://github.com/pykeen/pykeen/blob/799e224e772176703d796a9247bfcc179d343c6c/src/pykeen/evaluation/sklearn.py#L129-L142

I'd also say it would be worth adding a second introductory example based on this in the README.

**Comment by benedekrozemberczki** [comment]
I will look into this on Monday.

**Comment by benedekrozemberczki** [comment]
Exposed it! Thanks for the suggestion @cthoyt !
