### ISSUE TITLE
Why are there duplicate functions?

### ISSUE THREAD

**Issue by cthoyt** [AstraZeneca/rexmex#33]
I noticed that there are duplicate functions such as `miss_rate()`/`false_negative_rate()` and `fall_out()`/`false_positive_rate()`. What's the reason for the duplication?

**Comment by kajocina** [comment]
I believe it's there for convenience only. Some people are used to certain metric names within their subfield and might be looking for one vs the other.

**Comment by cthoyt** [comment]
Okay, that makes sense. Perhaps an alternative way to do it would just be to alias one function with another, rather than re-implementing it based on the other. This would make it a bit more explicit

**Comment by benedekrozemberczki** [comment]
Yes, that was the original idea, but generating documentation and making the equivalences explicit were considered to be more important.
