### ISSUE TITLE
Pandas versioning

### ISSUE THREAD

**Issue by Montana** [AstraZeneca/rexmex#53]
Hey AstraZeneca, 

The related line of code:

 https://github.com/AstraZeneca/rexmex/blob/44f453ff20e92569270b9e1cfcb75b44b7839128/setup.py#L3

Is it a strict requirement for `rexmex` to have `Pandas<1.3.5` or is this something we can modify in `rexmex` or `setup.py`? (if so I can open a related PR for it, much like the other question but formatted a bit better and notation to make it clear.)

Thanks, 
Montana Mendy

**Comment by benedekrozemberczki** [comment]
Do you want to open a PR?
